# Generated by Django 3.0.3 on 2020-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('title', models.TextField()),
                ('issue_no', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ST', 'Story'), ('BU', 'Bug'), ('TA', 'Task')], default='BU', max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IN', 'In Progress'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('details', models.TextField()),
            ],
        ),
    ]
