# Generated by Django 3.0.3 on 2020-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_issue', models.CharField(choices=[('ST', 'Story'), ('BU', 'Bug'), ('TA', 'Task')], default='BU', max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IN', 'In Progress'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('details', models.TextField()),
            ],
        ),
    ]
