# Generated by Django 3.0.3 on 2020-05-11 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('issue_no', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ST', 'Story'), ('BU', 'Bug'), ('TA', 'Task')], default='BU', max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IN', 'In Progress'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
