# Generated by Django 3.0.3 on 2020-04-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type_of_issue',
            new_name='type',
        ),
    ]
